[build]
  command = "yarn run build:prod"
  publish = "public"

# Plausible
[[redirects]]
  from = "/creme-brulee/js/script.js"
  to = "https://plausible.io/js/script.js"
  status = 200
[[redirects]]
  from = "/creme-brulee/api/event"
  to = "https://plausible.io/api/event"
  status = 200
