version: 2
jobs:
  build:
    docker:
      - image: node:12.10.0
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Check the code format
          command: yarn run format:ci
      - run:
          name: Lint the code
          command: yarn run lint
      - run:
          name: Test the code
          command: yarn run test
